### ISSUE TITLE
installation error minikube

### ISSUE THREAD

**Issue by stevieg27** [sse-secure-systems/connaisseur#59] opened 2020-11-11 14:31 UTC
**Describe the bug**
Followed the installation procedure for the minikube setup but the logs from connaissuer pod throws below error

1, Installation error

Error: timed out waiting for the condition
make: *** [Makefile:20: install] Error 1

2. Logs from pod

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/connaisseur/flask_server.py", line 114, in readyz
    notary_health = health_check(os.environ.get("NOTARY_SERVER"))
  File "/app/connaisseur/notary_api.py", line 37, in health_check
    response = requests.get(**request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='notary.harbor.domain', port=443): Max retries exceeded with url: /_notary_server/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa943883f40>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

INFO: 172.18.0.1 - - [11/Nov/2020 14:26:26] "GET /ready HTTP/1.1" 500 -
[2020-11-11 14:26:29,374] INFO: 172.18.0.1 - - [11/Nov/2020 14:26:29] "GET /health HTTP/1.1" 200 -

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu 20.04
 - minikube version: v1.13.1 - driver=docker
-  kubernetes version : v1.18.9

**Comment by Starkteetje** [comment] 2020-11-11 14:43
Hi @stevieg27 

judging from the Exception you were trying the local setup guide with self-hosted notary, right? The exception thrown suggests that the pod cannot resolve the notary server URL `notary.harbor.domain`. Since you mentin the driver docker, note the `If you use a different driver such as docker, you may run into problems with minikube, i.e. DNS settings for Harbor and Notary not propagating.` warning at the start of the local setup.

I don't know why the minikube DNS settings do not propagate with the docker driver, however if you want to monkey-patch the issue, you can put the output of `echo -e "\n$(minikube ip)\t\tcore.harbor.domain\n$(minikube ip)\t\tnotary.harbor.domain"` (on your machine) into the `/etc/hosts` file on the Connaisseur pods. Since doing so will probably take longer than the default [bootstrap timeout](https://github.com/sse-secure-systems/connaisseur/blob/master/helm/values.yaml#L18) you should increase that value before-hand.

However, if you can, consider using the virtualbox driver for the local setup.

Hope that helps for a start. Feel free to come back to ask further questions. Cheers,
Teetje

**Comment by stevieg27** [comment] 2020-11-11 14:51
Thanks for the reply. Yeah i have followed that tutorial. I have enabled ingress and ingress-dns as well in minikube. Also try to put the mentioned data in  hosts file  of 3 connaisseur pods. Since that the logs of  pods were showing this below:

INFO: 172.18.0.1 - - [11/Nov/2020 14:26:26] "GET /ready HTTP/1.1" 500 -
[2020-11-11 14:26:29,374] INFO: 172.18.0.1 - - [11/Nov/2020 14:26:29] "GET /health HTTP/1.1" 200 

does that mean its working or should I increase the timeout and see.

**Comment by Starkteetje** [comment] 2020-11-11 14:58
Yeah, that means the DNS is now working and the Connaisseur pods can access the Notary. However, I presume that if you run `kubectl get all` you see `pod/connaisseur-bootstrap-sentinel            0/1     Completed   0` or similar. This pod is started at the beginning [due to a chicken-egg problem](https://github.com/sse-secure-systems/connaisseur/blob/master/adr/ADR-1_connaisseur-bootstrap-sentinel.md) and after it completes the deployment will not be able to procede further (that's the timeout I linked earlier).

You can either try the deployment again with bigger timeout and then patch `/etc/hosts` again prior to the timeout completing or you can restart the `connaisseur-bootstrap-sentinel` pod manually and manually run the remaining steps of the [helm install script](https://github.com/sse-secure-systems/connaisseur/blob/master/scripts/helm_hook.sh#L7).
I realize both options are kind of shitty, but that's the problem of minikube DNS not working with the docker driver

**Comment by stevieg27** [comment] 2020-11-11 20:57
Thanks. Increased the timeout and patched the hosts to work this. Minikube with docker driver is a pain :(

**Comment by Starkteetje** [comment] 2020-11-12 08:10
Glad it worked out for you. Understanding the problem is resolved, I'll close this issue.

We'd also be happy to get any feedback you might have on both the documentation or Connaisseur once you've tested it, either as an issue or to connaisseur@securesystems.dev

**Closed by Starkteetje** 2020-11-12 08:10 UTC
