### ISSUE TITLE
Add support for keyless signatures for cosign

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#141] opened 2021-04-14 23:17 UTC
**Describe the feature**
Cosign offers yet another even more experimental feature: keyless signatures via OIDC. Connaisseur should attempt to support this based on Fulcio code signing certificates.

**Optional: Implementation ideas**
Not sure.

**Comment by phbelitz** [comment] 2024-07-26 14:12
duplicate of #1493

**Closed by phbelitz** 2024-07-26 14:12 UTC
