### ISSUE TITLE
Cannot able to install connaisseur giving error of time out due to atomic being set

### ISSUE THREAD

**Issue by n30gupta** [sse-secure-systems/connaisseur#445] opened 2021-12-07 12:23 UTC
Hi,
 I was trying to setup a use case where I have installed notary server locally in my kubernetes cluster as a container which runs on this URL => https://localhost:4443 and also local registry I installed as a container which runs on localhost:5000. 
So I have generated the key to sign the image with DCT and push my image into local registry and set the DOCKER_CONTENT_TRUST_SERVER=https://localhost:4443.

SO while validating the image with connaisseur I need to install connaisseur but I am getting below error:
**root@ubuntuserver:~/test/connaisseur# helm install connaisseur helm --atomic --create-namespace --namespace connaisseur
Error: INSTALLATION FAILED: release connaisseur failed, and has been uninstalled due to atomic being set: timed out waiting for the condition**

Please help me to resolve the issue.
Thanks!

**Comment by xopham** [comment] 2021-12-07 13:54
@n30gupta could you share some more details such as Kubernetes version, flavor (e.g. bare metal, Kind, microk8s, AKS, GKE, Openshift)? Also which resources do you see spinning up before installation fails? Could you share the `kubectl describe` of those resources?

The problem may be caused by the secure default securityContext. Please checkout and adjust `helm/values.yaml`: https://sse-secure-systems.github.io/connaisseur/v2.2.1/basics/#configure

Let me know if that helps 🙏

**Comment by n30gupta** [comment] 2021-12-07 18:43
@xopham I have installed notary locally and when I am giving the URL of my notary server https://localhost:4443 in helm/values.yaml file. So when installing connaisseur with this configuration I am facing the error but when I install with default configuration I am not facing any error.

Kubernetes is running on bare metal and it is on version 1.21

Is there any specific guide where there is a process of integrating local Notary server with connaisseur as in default configuration the notary uses docker hub url  notary.docker.io

**Comment by xopham** [comment] 2021-12-08 10:12
@n30gupta gotcha! Thanks for letting me know.
I found the issue. It is a problem with the json schema validation of the configuration: https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/res/config_schema.json#L40

```json
"pattern": "[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}"
```
This requires a full domain (e.g. `example.com`). Escalating to bug and should be fixed rather quickly.

**Closed** 2021-12-17 14:21 UTC
Labels: bug
